// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'icon': string;
  'icon2': string;
  'icon3': string;
  'img': string;
  'input': string;
  'left': string;
  'link': string;
  'mainy': string;
  'p': string;
  'p_1': string;
  'p_2': string;
  'right': string;
  'root': string;
  'textarea': string;
}
export const cssExports: CssExports;
export default cssExports;
