// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'cards': string;
  'h2': string;
  'h2_1': string;
  'hat': string;
  'rooot': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
