// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chart': string;
  'flower': string;
  'flower_1': string;
  'flower_2': string;
  'h1': string;
  'icons': string;
  'rooot': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
