version: '3.0'


services:

  sample-postgres:
    container_name: sample-postgres
    build: ./docker/postgres
    image: sample-postgres
    ports:
    - "127.0.0.1:5432:5432"
    networks:
      dev:
        aliases:
          - fucking_shit
    env_file:
      - .env
    volumes:
    - ./docker-data/postgres/data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/
    restart: always


  deanon-nodejs:
    container_name: deanon-nodejs
    build: ./docker/nodejs
    image: deanon-nodejs
    volumes:
      - .:/app
    ports:
      - 8090:3000
      - 5555:5555
    networks:
      dev:
        aliases:
          - fucking_shit_two
    env_file:
      - .env
    depends_on:
      - sample-postgres
    command: yarn prod
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - deanon-nodejs
      - sample-postgres
    networks:
      dev:
        aliases:
          - fucking_shit_three

networks:
  dev:
    external:
      name: dev

