// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about': string;
  'aboutUs': string;
  'admin': string;
  'icons': string;
  'link': string;
  'mainy': string;
  'p': string;
}
export const cssExports: CssExports;
export default cssExports;
