// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'frame': string;
  'framy': string;
  'hat': string;
  'head': string;
  'typography': string;
}
export const cssExports: CssExports;
export default cssExports;
