// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'icon': string;
  'mainy': string;
  'message': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
